#!/usr/bin/env python

# Copyright 2012 Jake Basile
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import os
import argparse
import yaubot.core

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('adapter', help='The adapter to use.')
    parser.add_argument('-p', '--package', help='Package names for scripts.', action='append')
    args = parser.parse_args()
    adapter = __import__('yaubot.adapters.' + args.adapter, fromlist=['run'])
    bot = yaubot.core.Yaubot()
    bot.load_scripts('yaubot.scripts.core')
    for package in args.package:
        bot.load_scripts(package)
    adapter.run(bot)
    
